// The OpenCode adapter: a generated plugin file that `leash init --opencode` drops into
// OpenCode's plugins dir. OpenCode hooks return void - there is no Claude/Codex-style
// "block the stop" - so the plugin works the only honest way the API allows:
//   - `chat.message` (a user message = turn start) runs `leash snapshot`;
//   - when the session goes idle (`session.status` idle, or the deprecated `session.idle`)
//     it runs `leash check --turn --json` once, and on a repair-band break sends the
//     reason back into the session as a follow-up prompt via `client.session.prompt`.
// Loop guard, mirroring Codex's stop_hook_active: at most one check and one nudge per
// user turn. Leash's own nudge is recognised (it starts with "Leash:") so it does not
// reset the snapshot. Verified against anomalyco/opencode: plugin event hook, the
// session.status / session.idle event schemas, chat.message input, client.session.prompt.

import { homedir } from 'node:os';
import { join } from 'node:path';
import { removeIfExists, writeFileEnsuringDir } from './files.js';

/** The generated plugin (plain ESM JavaScript; OpenCode loads it with Bun). */
export const OPENCODE_PLUGIN = `// Leash for OpenCode - generated by \`leash init --opencode\`. Do not edit; re-run init.
// Snapshots each user turn, checks it once when the session goes idle, and on a
// repair-band rule break sends the reason back as one follow-up prompt per turn.
export const LeashPlugin = async ({ client, $, directory }) => {
  const checked = new Set();
  const leash = (...args) => $\`leash \${args}\`.cwd(directory).quiet().nothrow();
  return {
    'chat.message': async (input, output) => {
      if (isLeashNudge(output && output.parts)) return;
      checked.delete(input.sessionID);
      await leash('snapshot');
    },
    event: async ({ event }) => {
      const id = idleSession(event);
      if (!id || checked.has(id)) return;
      checked.add(id);
      const result = await leash('check', '--turn', '--json');
      const reason = blockReason(String(result.stdout));
      if (!reason) return;
      await client.session.prompt({ path: { id }, body: { parts: [{ type: 'text', text: reason }] } });
    },
  };
};

function idleSession(event) {
  const props = (event && event.properties) || {};
  if (event.type === 'session.idle') return props.sessionID;
  if (event.type === 'session.status' && props.status && props.status.type === 'idle') return props.sessionID;
  return undefined;
}

function isLeashNudge(parts) {
  return (parts || []).some((p) => p && p.type === 'text' && String(p.text || '').startsWith('Leash:'));
}

function blockReason(stdout) {
  try {
    const decision = JSON.parse(stdout).decision;
    return decision && decision.decision === 'block' ? decision.reason : null;
  } catch {
    return null;
  }
}
`;

const PLUGIN_FILE = 'leash.js';

/** Project plugins live in `.opencode/plugins/`, global ones in `~/.config/opencode/plugins/`. */
export function opencodePluginPath(project: boolean): string {
  return project
    ? join('.opencode', 'plugins', PLUGIN_FILE)
    : join(homedir(), '.config', 'opencode', 'plugins', PLUGIN_FILE);
}

export function writeOpenCodePlugin(project: boolean): string {
  return writeFileEnsuringDir(opencodePluginPath(project), OPENCODE_PLUGIN);
}

export function removeOpenCodePlugin(project: boolean): string {
  return removeIfExists(opencodePluginPath(project));
}
